; PlatformIO Project Configuration File
; SistemaDeRiego - Arduino Uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino

; Serial monitor speed
monitor_speed = 9600

; Unit testing
test_framework = unity

[env:native]
platform = native
test_framework = unity
